// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_8than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn-2zdOmljplVhOxUwbeuFdQ1uq43JrJI',
    appId: '1:514654202616:android:a5f9fb443cf8b12ea0e90d',
    messagingSenderId: '514654202616',
    projectId: 'fir-demo-91791',
    storageBucket: 'fir-demo-91791.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuaegfg_5oH-APQUbuWyuZfSeJ25jtwV4',
    appId: '1:514654202616:ios:de70d0e27feaed53a0e90d',
    messagingSenderId: '514654202616',
    projectId: 'fir-demo-91791',
    storageBucket: 'fir-demo-91791.appspot.com',
    iosClientId: '514654202616-2remnf2phnv1a0jjbgf8912e93nqfq0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseEx',
  );
}
